### ISSUE TITLE
Macosx error on bonjour

### ISSUE THREAD

**Issue by tampas** [basilfx/flask-daapserver#2]
hi, i'm trying to run flask with subsonic but i cannot announce the flask library to my iTunes players.
When running the server with the Zeroconf announcement on, i get this error:

> File "/Library/Python/2.7/site-packages/zeroconf.py", line 203, in service_type_name
>     "Type must end with '._tcp.local.' or '._udp.local.'")
> zeroconf.BadTypeInNameException: Type must end with '._tcp.local.' or '._udp.local.'

Any advice on resolving this issue?
Best regards

**Comment by basilfx** [comment]
It is in the code. See [here](https://github.com/basilfx/flask-daapserver/blob/6c21b82b5ecbeb90035eb0d438c523d6420285d7/daapserver/bonjour.py#L95).

Which version of Python (`python --version`), Zeroconf (`pip freeze`) and OS (`uname -a`)?

**Comment by tampas** [comment]
> zeroconf==0.17.6
> Python 2.7.10
> 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**Comment by basilfx** [comment]
Strange. I cannot see why this is happening. Can you try an older version of zeroconf? Any chance to debug what is passed on to [this](https://github.com/jstasiak/python-zeroconf/blob/0.17.6/zeroconf.py#L169) method?
